# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "slave", autostart: true do |slave|
    slave.vm.hostname = "boltslave"
    slave.vm.box = "bolt/slave"
    slave.vm.network "private_network", ip: "192.168.152.11", virtualbox__intnet: true
  end

  config.vm.define "master", autostart: true do |master|
    master.vm.hostname = "boltmaster"
    master.vm.box = "bolt/master"
    master.vm.network "private_network", ip: "192.168.152.10", virtualbox__intnet: true
    master.vm.provision "shell", inline: <<-SHELL
      bolt
    SHELL
  end

end
